### ISSUE TITLE
Замечания по основной игре

### ISSUE THREAD

**Issue by sergey-shambir** [JokerSSmile/Projects#1]
- функция InitializeLevel возвращает магические числа, следует возвращать либо именованные численные константы, либо константы enum-типа.
- в DrawPlayersHealth переменную i следует объявить внутри for - нет смысла объявлять её так далеко от цикла
- магическое число в параметре функции CheckEnemyCollidesPlayer, возможно, лучше вообще использовать и передавать std::vector
- функция main слишком большая, надо её разгрузить и выделить отдельные шаги в функции

**Comment by JokerSSmile** [comment]
Исправлено
